### ISSUE TITLE
Propose changes to avoid an exception and old APIs

### ISSUE THREAD

**Issue by MrTroble** [hammerniko/de.itg.hgs.db#1]
https://github.com/hammerniko/de.itg.hgs.db/blob/eecf3179beb67b042e61b017efb7df28c71b00c8/DB/src/gui/MyFiles.java#L41-L74

Proposed

```java
public static void saveFile(File f, String path) {
		Path pathToOut = Paths.get(path);
		Path pathFromIn = Paths.get(f.getAbsolutePath());
		if(!Files.exists(pathFromIn)) {
			JOptionPane.showMessageDialog(parent, "File not found", "IO Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		try {
                        // EDIT: No checks needed here. Just a copy option in case the file already exists
			Files.copy(pathFromIn, pathToOut, StandardCopyOption.REPLACE_EXISTING);
		} catch (IOException e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(parent, "Schreib-Lese Fehler", "IO Error", JOptionPane.ERROR_MESSAGE);
		}
	}
```
Advantages:
* Reduced code size
* Faster (Reduced exception usage, No usage of buffers, already optimized code from API) 
* No buffer usage, reduced risk of memory leaks
* Less overhead
* Better readability bc of a more procedural style of code
* This matches the underlining code structure from the os

Disadvantages:
* Conversion from File to Path API introducing overhead
  * Fixable by using the NIO standart lib all over the place

**Comment by hammerniko** [comment]
Thanks
